#!/usr/bin/env bash
set -e

HASH=${1-master}

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

echo -e ${GREEN}Updating dapptools to commit ${RED}${HASH}${GREEN}!${NC}

nix-env -f https://github.com/dapphub/dapptools/archive/${HASH}.tar.gz -iA dapp hevm seth