#!/usr/bin/env bash
set -e

GREEN="\033[0;32m"
RED="\033[0;31m"
NC="\033[0m"

echo -e ${GREEN}Installing ${RED}duppgrade${GREEN} to ${RED}/usr/local/bin${GREEN}!${NC}

DUPPGRADE='#!/usr/bin/env bash
set -e

GREEN="\033[0;32m"
RED="\033[0;31m"
NC="\033[0m"

if [[ "$1" == *dapptools* ]]
then
    REPO=$1
    COMMIT=${2-master}
else
    REPO="dapphub/dapptools"
    COMMIT=${1-master}
fi

echo -e ${GREEN}Updating ${RED}dapptools${GREEN} to ${RED}${REPO}${GREEN} at commit ${RED}${COMMIT}${GREEN}!${NC}

nix-env -f https://github.com/${REPO}/archive/${COMMIT}.tar.gz -iA dapp hevm seth'

BINARY="/usr/local/bin/duppgrade"
echo "$DUPPGRADE" > $BINARY
chmod +x $BINARY