#!/usr/bin/env bash
set -e

GREEN="\033[0;32m"
RED="\033[0;31m"
NC="\033[0m"

echo -e ${GREEN}Installing ${RED}duppgrade${GREEN} to ${RED}/usr/local/bin${GREEN}!${NC}

DUPPGRADE='#!/usr/bin/env bash
set -e

HASH=${1-master}

GREEN="\033[0;32m"
RED="\033[0;31m"
NC="\033[0m"

echo -e ${GREEN}Updating dapptools to commit ${RED}${HASH}${GREEN}!${NC}

nix-env -f https://github.com/dapphub/dapptools/archive/${HASH}.tar.gz -iA dapp hevm seth'

BINARY="/usr/local/bin/duppgrade"
echo "$DUPPGRADE" > $BINARY
chmod +x $BINARY